matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install unoconv
language: node_js
node_js:
  - 0.12
  - 4.0
  - 5.0
  - 6.0
